/**
  * \file VecBrlyVDpch.h
  * vector VecBrlyVDpch (implementation)
  * \author Alexander Wirthmueller
  * \date created: 8 Jan 2018
  * \date modified: 8 Jan 2018
  */

#ifdef _WIN32
	#include "stdafx.h"
#endif

#include "VecBrlyVDpch.h"

/******************************************************************************
 namespace VecBrlyVDpch
 ******************************************************************************/

uint VecBrlyVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s.compare("dpchengbrlyack") == 0) return DPCHENGBRLYACK;
	else if (s.compare("dpchengbrlyalert") == 0) return DPCHENGBRLYALERT;
	else if (s.compare("dpchengbrlycon1nrelaydata") == 0) return DPCHENGBRLYCON1NRELAYDATA;
	else if (s.compare("dpchengbrlyconconmnequipmentdata") == 0) return DPCHENGBRLYCONCONMNEQUIPMENTDATA;
	else if (s.compare("dpchengbrlycondata") == 0) return DPCHENGBRLYCONDATA;
	else if (s.compare("dpchengbrlycondetaildata") == 0) return DPCHENGBRLYCONDETAILDATA;
	else if (s.compare("dpchengbrlyconfirm") == 0) return DPCHENGBRLYCONFIRM;
	else if (s.compare("dpchengbrlyconheadbardata") == 0) return DPCHENGBRLYCONHEADBARDATA;
	else if (s.compare("dpchengbrlyconlistdata") == 0) return DPCHENGBRLYCONLISTDATA;
	else if (s.compare("dpchengbrlyconmapdata") == 0) return DPCHENGBRLYCONMAPDATA;
	else if (s.compare("dpchengbrlyconmapimage") == 0) return DPCHENGBRLYCONMAPIMAGE;
	else if (s.compare("dpchengbrlyconmnflightdata") == 0) return DPCHENGBRLYCONMNFLIGHTDATA;
	else if (s.compare("dpchengbrlyconmnsegmentdata") == 0) return DPCHENGBRLYCONMNSEGMENTDATA;
	else if (s.compare("dpchengbrlyconpredata") == 0) return DPCHENGBRLYCONPREDATA;
	else if (s.compare("dpchengbrlyconrecdata") == 0) return DPCHENGBRLYCONRECDATA;
	else if (s.compare("dpchengbrlyconref1nsegmentdata") == 0) return DPCHENGBRLYCONREF1NSEGMENTDATA;
	else if (s.compare("dpchengbrlyfildata") == 0) return DPCHENGBRLYFILDATA;
	else if (s.compare("dpchengbrlyfildetaildata") == 0) return DPCHENGBRLYFILDETAILDATA;
	else if (s.compare("dpchengbrlyfilheadbardata") == 0) return DPCHENGBRLYFILHEADBARDATA;
	else if (s.compare("dpchengbrlyfillistdata") == 0) return DPCHENGBRLYFILLISTDATA;
	else if (s.compare("dpchengbrlyfilrecdata") == 0) return DPCHENGBRLYFILRECDATA;
	else if (s.compare("dpchengbrlyflt1nconnectiondata") == 0) return DPCHENGBRLYFLT1NCONNECTIONDATA;
	else if (s.compare("dpchengbrlyfltdata") == 0) return DPCHENGBRLYFLTDATA;
	else if (s.compare("dpchengbrlyfltdetaildata") == 0) return DPCHENGBRLYFLTDETAILDATA;
	else if (s.compare("dpchengbrlyflteqp1nnodedata") == 0) return DPCHENGBRLYFLTEQP1NNODEDATA;
	else if (s.compare("dpchengbrlyflteqpmnconnectiondata") == 0) return DPCHENGBRLYFLTEQPMNCONNECTIONDATA;
	else if (s.compare("dpchengbrlyfltfafawaypointdata") == 0) return DPCHENGBRLYFLTFAFAWAYPOINTDATA;
	else if (s.compare("dpchengbrlyfltheadbardata") == 0) return DPCHENGBRLYFLTHEADBARDATA;
	else if (s.compare("dpchengbrlyfltlistdata") == 0) return DPCHENGBRLYFLTLISTDATA;
	else if (s.compare("dpchengbrlyfltmnconnectiondata") == 0) return DPCHENGBRLYFLTMNCONNECTIONDATA;
	else if (s.compare("dpchengbrlyfltmnlocationdata") == 0) return DPCHENGBRLYFLTMNLOCATIONDATA;
	else if (s.compare("dpchengbrlyfltorgmnflightdata") == 0) return DPCHENGBRLYFLTORGMNFLIGHTDATA;
	else if (s.compare("dpchengbrlyfltpredata") == 0) return DPCHENGBRLYFLTPREDATA;
	else if (s.compare("dpchengbrlyfltrecdata") == 0) return DPCHENGBRLYFLTRECDATA;
	else if (s.compare("dpchengbrlyfltref1nsegmentdata") == 0) return DPCHENGBRLYFLTREF1NSEGMENTDATA;
	else if (s.compare("dpchengbrlyleg1nflightdata") == 0) return DPCHENGBRLYLEG1NFLIGHTDATA;
	else if (s.compare("dpchengbrlylegcor1nconnectiondata") == 0) return DPCHENGBRLYLEGCOR1NCONNECTIONDATA;
	else if (s.compare("dpchengbrlylegdata") == 0) return DPCHENGBRLYLEGDATA;
	else if (s.compare("dpchengbrlylegdetaildata") == 0) return DPCHENGBRLYLEGDETAILDATA;
	else if (s.compare("dpchengbrlylegheadbardata") == 0) return DPCHENGBRLYLEGHEADBARDATA;
	else if (s.compare("dpchengbrlyleglistdata") == 0) return DPCHENGBRLYLEGLISTDATA;
	else if (s.compare("dpchengbrlylegmapdata") == 0) return DPCHENGBRLYLEGMAPDATA;
	else if (s.compare("dpchengbrlylegmapimage") == 0) return DPCHENGBRLYLEGMAPIMAGE;
	else if (s.compare("dpchengbrlylegmnlocationdata") == 0) return DPCHENGBRLYLEGMNLOCATIONDATA;
	else if (s.compare("dpchengbrlylegorgmnlegdata") == 0) return DPCHENGBRLYLEGORGMNLEGDATA;
	else if (s.compare("dpchengbrlylegpredata") == 0) return DPCHENGBRLYLEGPREDATA;
	else if (s.compare("dpchengbrlylegrecdata") == 0) return DPCHENGBRLYLEGRECDATA;
	else if (s.compare("dpchengbrlylocbgn1nlegdata") == 0) return DPCHENGBRLYLOCBGN1NLEGDATA;
	else if (s.compare("dpchengbrlylocdata") == 0) return DPCHENGBRLYLOCDATA;
	else if (s.compare("dpchengbrlylocdetaildata") == 0) return DPCHENGBRLYLOCDETAILDATA;
	else if (s.compare("dpchengbrlylocend1nlegdata") == 0) return DPCHENGBRLYLOCEND1NLEGDATA;
	else if (s.compare("dpchengbrlyloceqp1nnodedata") == 0) return DPCHENGBRLYLOCEQP1NNODEDATA;
	else if (s.compare("dpchengbrlyloceqpmnconnectiondata") == 0) return DPCHENGBRLYLOCEQPMNCONNECTIONDATA;
	else if (s.compare("dpchengbrlylocheadbardata") == 0) return DPCHENGBRLYLOCHEADBARDATA;
	else if (s.compare("dpchengbrlyloclistdata") == 0) return DPCHENGBRLYLOCLISTDATA;
	else if (s.compare("dpchengbrlylocmapdata") == 0) return DPCHENGBRLYLOCMAPDATA;
	else if (s.compare("dpchengbrlylocmapimage") == 0) return DPCHENGBRLYLOCMAPIMAGE;
	else if (s.compare("dpchengbrlylocmnflightdata") == 0) return DPCHENGBRLYLOCMNFLIGHTDATA;
	else if (s.compare("dpchengbrlylocmnlegdata") == 0) return DPCHENGBRLYLOCMNLEGDATA;
	else if (s.compare("dpchengbrlylocmnsegmentdata") == 0) return DPCHENGBRLYLOCMNSEGMENTDATA;
	else if (s.compare("dpchengbrlylocproxorgmnlocationdata") == 0) return DPCHENGBRLYLOCPROXORGMNLOCATIONDATA;
	else if (s.compare("dpchengbrlylocrecdata") == 0) return DPCHENGBRLYLOCRECDATA;
	else if (s.compare("dpchengbrlylocvisorgmnlocationdata") == 0) return DPCHENGBRLYLOCVISORGMNLOCATIONDATA;
	else if (s.compare("dpchengbrlynavadmindata") == 0) return DPCHENGBRLYNAVADMINDATA;
	else if (s.compare("dpchengbrlynavbasedata") == 0) return DPCHENGBRLYNAVBASEDATA;
	else if (s.compare("dpchengbrlynavconnectdata") == 0) return DPCHENGBRLYNAVCONNECTDATA;
	else if (s.compare("dpchengbrlynavdata") == 0) return DPCHENGBRLYNAVDATA;
	else if (s.compare("dpchengbrlynavheadbardata") == 0) return DPCHENGBRLYNAVHEADBARDATA;
	else if (s.compare("dpchengbrlyopr1nequipmentdata") == 0) return DPCHENGBRLYOPR1NEQUIPMENTDATA;
	else if (s.compare("dpchengbrlyoprdata") == 0) return DPCHENGBRLYOPRDATA;
	else if (s.compare("dpchengbrlyoprdetaildata") == 0) return DPCHENGBRLYOPRDETAILDATA;
	else if (s.compare("dpchengbrlyoprheadbardata") == 0) return DPCHENGBRLYOPRHEADBARDATA;
	else if (s.compare("dpchengbrlyoprlistdata") == 0) return DPCHENGBRLYOPRLISTDATA;
	else if (s.compare("dpchengbrlyoprrecdata") == 0) return DPCHENGBRLYOPRRECDATA;
	else if (s.compare("dpchengbrlyprsadetaildata") == 0) return DPCHENGBRLYPRSADETAILDATA;
	else if (s.compare("dpchengbrlyprsdata") == 0) return DPCHENGBRLYPRSDATA;
	else if (s.compare("dpchengbrlyprsdetaildata") == 0) return DPCHENGBRLYPRSDETAILDATA;
	else if (s.compare("dpchengbrlyprsheadbardata") == 0) return DPCHENGBRLYPRSHEADBARDATA;
	else if (s.compare("dpchengbrlyprslistdata") == 0) return DPCHENGBRLYPRSLISTDATA;
	else if (s.compare("dpchengbrlyprsrecdata") == 0) return DPCHENGBRLYPRSRECDATA;
	else if (s.compare("dpchengbrlypty1nequipmentdata") == 0) return DPCHENGBRLYPTY1NEQUIPMENTDATA;
	else if (s.compare("dpchengbrlyptydata") == 0) return DPCHENGBRLYPTYDATA;
	else if (s.compare("dpchengbrlyptydetaildata") == 0) return DPCHENGBRLYPTYDETAILDATA;
	else if (s.compare("dpchengbrlyptyheadbardata") == 0) return DPCHENGBRLYPTYHEADBARDATA;
	else if (s.compare("dpchengbrlyptylistdata") == 0) return DPCHENGBRLYPTYLISTDATA;
	else if (s.compare("dpchengbrlyptyrecdata") == 0) return DPCHENGBRLYPTYRECDATA;
	else if (s.compare("dpchengbrlyreg1nlocationdata") == 0) return DPCHENGBRLYREG1NLOCATIONDATA;
	else if (s.compare("dpchengbrlyregadstswitchdata") == 0) return DPCHENGBRLYREGADSTSWITCHDATA;
	else if (s.compare("dpchengbrlyregdata") == 0) return DPCHENGBRLYREGDATA;
	else if (s.compare("dpchengbrlyregdetaildata") == 0) return DPCHENGBRLYREGDETAILDATA;
	else if (s.compare("dpchengbrlyregheadbardata") == 0) return DPCHENGBRLYREGHEADBARDATA;
	else if (s.compare("dpchengbrlyreglistdata") == 0) return DPCHENGBRLYREGLISTDATA;
	else if (s.compare("dpchengbrlyregrecdata") == 0) return DPCHENGBRLYREGRECDATA;
	else if (s.compare("dpchengbrlyregsup1nregiondata") == 0) return DPCHENGBRLYREGSUP1NREGIONDATA;
	else if (s.compare("dpchengbrlyrly1nnodedata") == 0) return DPCHENGBRLYRLY1NNODEDATA;
	else if (s.compare("dpchengbrlyrlydata") == 0) return DPCHENGBRLYRLYDATA;
	else if (s.compare("dpchengbrlyrlydetaildata") == 0) return DPCHENGBRLYRLYDETAILDATA;
	else if (s.compare("dpchengbrlyrlyheadbardata") == 0) return DPCHENGBRLYRLYHEADBARDATA;
	else if (s.compare("dpchengbrlyrlylistdata") == 0) return DPCHENGBRLYRLYLISTDATA;
	else if (s.compare("dpchengbrlyrlyrecdata") == 0) return DPCHENGBRLYRLYRECDATA;
	else if (s.compare("dpchengbrlysegdata") == 0) return DPCHENGBRLYSEGDATA;
	else if (s.compare("dpchengbrlysegdetaildata") == 0) return DPCHENGBRLYSEGDETAILDATA;
	else if (s.compare("dpchengbrlysegheadbardata") == 0) return DPCHENGBRLYSEGHEADBARDATA;
	else if (s.compare("dpchengbrlyseglistdata") == 0) return DPCHENGBRLYSEGLISTDATA;
	else if (s.compare("dpchengbrlysegmnconnectiondata") == 0) return DPCHENGBRLYSEGMNCONNECTIONDATA;
	else if (s.compare("dpchengbrlysegmnlocationdata") == 0) return DPCHENGBRLYSEGMNLOCATIONDATA;
	else if (s.compare("dpchengbrlysegorgmnsegmentdata") == 0) return DPCHENGBRLYSEGORGMNSEGMENTDATA;
	else if (s.compare("dpchengbrlysegpredata") == 0) return DPCHENGBRLYSEGPREDATA;
	else if (s.compare("dpchengbrlysegrecdata") == 0) return DPCHENGBRLYSEGRECDATA;
	else if (s.compare("dpchengbrlysuspend") == 0) return DPCHENGBRLYSUSPEND;
	else if (s.compare("dpchengbrlyttb1nflightdata") == 0) return DPCHENGBRLYTTB1NFLIGHTDATA;
	else if (s.compare("dpchengbrlyttbdata") == 0) return DPCHENGBRLYTTBDATA;
	else if (s.compare("dpchengbrlyttbdetaildata") == 0) return DPCHENGBRLYTTBDETAILDATA;
	else if (s.compare("dpchengbrlyttbheadbardata") == 0) return DPCHENGBRLYTTBHEADBARDATA;
	else if (s.compare("dpchengbrlyttblistdata") == 0) return DPCHENGBRLYTTBLISTDATA;
	else if (s.compare("dpchengbrlyttbrecdata") == 0) return DPCHENGBRLYTTBRECDATA;
	else if (s.compare("dpchengbrlyttbref1nfiledata") == 0) return DPCHENGBRLYTTBREF1NFILEDATA;
	else if (s.compare("dpchengbrlyusgaaccessdata") == 0) return DPCHENGBRLYUSGAACCESSDATA;
	else if (s.compare("dpchengbrlyusgdata") == 0) return DPCHENGBRLYUSGDATA;
	else if (s.compare("dpchengbrlyusgdetaildata") == 0) return DPCHENGBRLYUSGDETAILDATA;
	else if (s.compare("dpchengbrlyusgheadbardata") == 0) return DPCHENGBRLYUSGHEADBARDATA;
	else if (s.compare("dpchengbrlyusglistdata") == 0) return DPCHENGBRLYUSGLISTDATA;
	else if (s.compare("dpchengbrlyusgmnuserdata") == 0) return DPCHENGBRLYUSGMNUSERDATA;
	else if (s.compare("dpchengbrlyusgrecdata") == 0) return DPCHENGBRLYUSGRECDATA;
	else if (s.compare("dpchengbrlyusr1nsessiondata") == 0) return DPCHENGBRLYUSR1NSESSIONDATA;
	else if (s.compare("dpchengbrlyusraaccessdata") == 0) return DPCHENGBRLYUSRAACCESSDATA;
	else if (s.compare("dpchengbrlyusrdata") == 0) return DPCHENGBRLYUSRDATA;
	else if (s.compare("dpchengbrlyusrdetaildata") == 0) return DPCHENGBRLYUSRDETAILDATA;
	else if (s.compare("dpchengbrlyusrheadbardata") == 0) return DPCHENGBRLYUSRHEADBARDATA;
	else if (s.compare("dpchengbrlyusrlistdata") == 0) return DPCHENGBRLYUSRLISTDATA;
	else if (s.compare("dpchengbrlyusrmnusergroupdata") == 0) return DPCHENGBRLYUSRMNUSERGROUPDATA;
	else if (s.compare("dpchengbrlyusrrecdata") == 0) return DPCHENGBRLYUSRRECDATA;
	else if (s.compare("dpchengdlgbrlyconnewdata") == 0) return DPCHENGDLGBRLYCONNEWDATA;
	else if (s.compare("dpchengdlgbrlylegnewdata") == 0) return DPCHENGDLGBRLYLEGNEWDATA;
	else if (s.compare("dpchengdlgbrlynavloainidata") == 0) return DPCHENGDLGBRLYNAVLOAINIDATA;
	else if (s.compare("dpchengdlgbrlyttbimpfltdata") == 0) return DPCHENGDLGBRLYTTBIMPFLTDATA;
	else if (s.compare("dpchengdlgbrlyttbnewdata") == 0) return DPCHENGDLGBRLYTTBNEWDATA;
	else if (s.compare("dpchengdlgbrlyttbtrlorigdata") == 0) return DPCHENGDLGBRLYTTBTRLORIGDATA;
	else if (s.compare("dpchengsessbrlydata") == 0) return DPCHENGSESSBRLYDATA;
	else if (s.compare("dpchappbrlyalert") == 0) return DPCHAPPBRLYALERT;
	else if (s.compare("dpchappbrlycon1nrelaydata") == 0) return DPCHAPPBRLYCON1NRELAYDATA;
	else if (s.compare("dpchappbrlycon1nrelaydo") == 0) return DPCHAPPBRLYCON1NRELAYDO;
	else if (s.compare("dpchappbrlyconconmnequipmentdata") == 0) return DPCHAPPBRLYCONCONMNEQUIPMENTDATA;
	else if (s.compare("dpchappbrlyconconmnequipmentdo") == 0) return DPCHAPPBRLYCONCONMNEQUIPMENTDO;
	else if (s.compare("dpchappbrlycondetaildata") == 0) return DPCHAPPBRLYCONDETAILDATA;
	else if (s.compare("dpchappbrlycondetaildo") == 0) return DPCHAPPBRLYCONDETAILDO;
	else if (s.compare("dpchappbrlycondo") == 0) return DPCHAPPBRLYCONDO;
	else if (s.compare("dpchappbrlyconlistdata") == 0) return DPCHAPPBRLYCONLISTDATA;
	else if (s.compare("dpchappbrlyconlistdo") == 0) return DPCHAPPBRLYCONLISTDO;
	else if (s.compare("dpchappbrlyconmapdata") == 0) return DPCHAPPBRLYCONMAPDATA;
	else if (s.compare("dpchappbrlyconmapdo") == 0) return DPCHAPPBRLYCONMAPDO;
	else if (s.compare("dpchappbrlyconmnflightdata") == 0) return DPCHAPPBRLYCONMNFLIGHTDATA;
	else if (s.compare("dpchappbrlyconmnflightdo") == 0) return DPCHAPPBRLYCONMNFLIGHTDO;
	else if (s.compare("dpchappbrlyconmnsegmentdata") == 0) return DPCHAPPBRLYCONMNSEGMENTDATA;
	else if (s.compare("dpchappbrlyconmnsegmentdo") == 0) return DPCHAPPBRLYCONMNSEGMENTDO;
	else if (s.compare("dpchappbrlyconpredata") == 0) return DPCHAPPBRLYCONPREDATA;
	else if (s.compare("dpchappbrlyconrecdo") == 0) return DPCHAPPBRLYCONRECDO;
	else if (s.compare("dpchappbrlyconref1nsegmentdata") == 0) return DPCHAPPBRLYCONREF1NSEGMENTDATA;
	else if (s.compare("dpchappbrlyconref1nsegmentdo") == 0) return DPCHAPPBRLYCONREF1NSEGMENTDO;
	else if (s.compare("dpchappbrlyfildetaildata") == 0) return DPCHAPPBRLYFILDETAILDATA;
	else if (s.compare("dpchappbrlyfildetaildo") == 0) return DPCHAPPBRLYFILDETAILDO;
	else if (s.compare("dpchappbrlyfildo") == 0) return DPCHAPPBRLYFILDO;
	else if (s.compare("dpchappbrlyfillistdata") == 0) return DPCHAPPBRLYFILLISTDATA;
	else if (s.compare("dpchappbrlyfillistdo") == 0) return DPCHAPPBRLYFILLISTDO;
	else if (s.compare("dpchappbrlyfilrecdo") == 0) return DPCHAPPBRLYFILRECDO;
	else if (s.compare("dpchappbrlyflt1nconnectiondata") == 0) return DPCHAPPBRLYFLT1NCONNECTIONDATA;
	else if (s.compare("dpchappbrlyflt1nconnectiondo") == 0) return DPCHAPPBRLYFLT1NCONNECTIONDO;
	else if (s.compare("dpchappbrlyfltdetaildata") == 0) return DPCHAPPBRLYFLTDETAILDATA;
	else if (s.compare("dpchappbrlyfltdetaildo") == 0) return DPCHAPPBRLYFLTDETAILDO;
	else if (s.compare("dpchappbrlyfltdo") == 0) return DPCHAPPBRLYFLTDO;
	else if (s.compare("dpchappbrlyflteqp1nnodedata") == 0) return DPCHAPPBRLYFLTEQP1NNODEDATA;
	else if (s.compare("dpchappbrlyflteqp1nnodedo") == 0) return DPCHAPPBRLYFLTEQP1NNODEDO;
	else if (s.compare("dpchappbrlyflteqpmnconnectiondata") == 0) return DPCHAPPBRLYFLTEQPMNCONNECTIONDATA;
	else if (s.compare("dpchappbrlyflteqpmnconnectiondo") == 0) return DPCHAPPBRLYFLTEQPMNCONNECTIONDO;
	else if (s.compare("dpchappbrlyfltfafawaypointdata") == 0) return DPCHAPPBRLYFLTFAFAWAYPOINTDATA;
	else if (s.compare("dpchappbrlyfltfafawaypointdo") == 0) return DPCHAPPBRLYFLTFAFAWAYPOINTDO;
	else if (s.compare("dpchappbrlyfltlistdata") == 0) return DPCHAPPBRLYFLTLISTDATA;
	else if (s.compare("dpchappbrlyfltlistdo") == 0) return DPCHAPPBRLYFLTLISTDO;
	else if (s.compare("dpchappbrlyfltmnconnectiondata") == 0) return DPCHAPPBRLYFLTMNCONNECTIONDATA;
	else if (s.compare("dpchappbrlyfltmnconnectiondo") == 0) return DPCHAPPBRLYFLTMNCONNECTIONDO;
	else if (s.compare("dpchappbrlyfltmnlocationdata") == 0) return DPCHAPPBRLYFLTMNLOCATIONDATA;
	else if (s.compare("dpchappbrlyfltmnlocationdo") == 0) return DPCHAPPBRLYFLTMNLOCATIONDO;
	else if (s.compare("dpchappbrlyfltorgmnflightdata") == 0) return DPCHAPPBRLYFLTORGMNFLIGHTDATA;
	else if (s.compare("dpchappbrlyfltorgmnflightdo") == 0) return DPCHAPPBRLYFLTORGMNFLIGHTDO;
	else if (s.compare("dpchappbrlyfltpredata") == 0) return DPCHAPPBRLYFLTPREDATA;
	else if (s.compare("dpchappbrlyfltrecdo") == 0) return DPCHAPPBRLYFLTRECDO;
	else if (s.compare("dpchappbrlyfltref1nsegmentdata") == 0) return DPCHAPPBRLYFLTREF1NSEGMENTDATA;
	else if (s.compare("dpchappbrlyfltref1nsegmentdo") == 0) return DPCHAPPBRLYFLTREF1NSEGMENTDO;
	else if (s.compare("dpchappbrlyinit") == 0) return DPCHAPPBRLYINIT;
	else if (s.compare("dpchappbrlyleg1nflightdata") == 0) return DPCHAPPBRLYLEG1NFLIGHTDATA;
	else if (s.compare("dpchappbrlyleg1nflightdo") == 0) return DPCHAPPBRLYLEG1NFLIGHTDO;
	else if (s.compare("dpchappbrlylegcor1nconnectiondata") == 0) return DPCHAPPBRLYLEGCOR1NCONNECTIONDATA;
	else if (s.compare("dpchappbrlylegcor1nconnectiondo") == 0) return DPCHAPPBRLYLEGCOR1NCONNECTIONDO;
	else if (s.compare("dpchappbrlylegdetaildata") == 0) return DPCHAPPBRLYLEGDETAILDATA;
	else if (s.compare("dpchappbrlylegdetaildo") == 0) return DPCHAPPBRLYLEGDETAILDO;
	else if (s.compare("dpchappbrlylegdo") == 0) return DPCHAPPBRLYLEGDO;
	else if (s.compare("dpchappbrlyleglistdata") == 0) return DPCHAPPBRLYLEGLISTDATA;
	else if (s.compare("dpchappbrlyleglistdo") == 0) return DPCHAPPBRLYLEGLISTDO;
	else if (s.compare("dpchappbrlylegmapdata") == 0) return DPCHAPPBRLYLEGMAPDATA;
	else if (s.compare("dpchappbrlylegmapdo") == 0) return DPCHAPPBRLYLEGMAPDO;
	else if (s.compare("dpchappbrlylegmnlocationdata") == 0) return DPCHAPPBRLYLEGMNLOCATIONDATA;
	else if (s.compare("dpchappbrlylegmnlocationdo") == 0) return DPCHAPPBRLYLEGMNLOCATIONDO;
	else if (s.compare("dpchappbrlylegorgmnlegdata") == 0) return DPCHAPPBRLYLEGORGMNLEGDATA;
	else if (s.compare("dpchappbrlylegorgmnlegdo") == 0) return DPCHAPPBRLYLEGORGMNLEGDO;
	else if (s.compare("dpchappbrlylegpredata") == 0) return DPCHAPPBRLYLEGPREDATA;
	else if (s.compare("dpchappbrlylegrecdo") == 0) return DPCHAPPBRLYLEGRECDO;
	else if (s.compare("dpchappbrlylocbgn1nlegdata") == 0) return DPCHAPPBRLYLOCBGN1NLEGDATA;
	else if (s.compare("dpchappbrlylocbgn1nlegdo") == 0) return DPCHAPPBRLYLOCBGN1NLEGDO;
	else if (s.compare("dpchappbrlylocdetaildata") == 0) return DPCHAPPBRLYLOCDETAILDATA;
	else if (s.compare("dpchappbrlylocdetaildo") == 0) return DPCHAPPBRLYLOCDETAILDO;
	else if (s.compare("dpchappbrlylocdo") == 0) return DPCHAPPBRLYLOCDO;
	else if (s.compare("dpchappbrlylocend1nlegdata") == 0) return DPCHAPPBRLYLOCEND1NLEGDATA;
	else if (s.compare("dpchappbrlylocend1nlegdo") == 0) return DPCHAPPBRLYLOCEND1NLEGDO;
	else if (s.compare("dpchappbrlyloceqp1nnodedata") == 0) return DPCHAPPBRLYLOCEQP1NNODEDATA;
	else if (s.compare("dpchappbrlyloceqp1nnodedo") == 0) return DPCHAPPBRLYLOCEQP1NNODEDO;
	else if (s.compare("dpchappbrlyloceqpmnconnectiondata") == 0) return DPCHAPPBRLYLOCEQPMNCONNECTIONDATA;
	else if (s.compare("dpchappbrlyloceqpmnconnectiondo") == 0) return DPCHAPPBRLYLOCEQPMNCONNECTIONDO;
	else if (s.compare("dpchappbrlyloclistdata") == 0) return DPCHAPPBRLYLOCLISTDATA;
	else if (s.compare("dpchappbrlyloclistdo") == 0) return DPCHAPPBRLYLOCLISTDO;
	else if (s.compare("dpchappbrlylocmapdata") == 0) return DPCHAPPBRLYLOCMAPDATA;
	else if (s.compare("dpchappbrlylocmapdo") == 0) return DPCHAPPBRLYLOCMAPDO;
	else if (s.compare("dpchappbrlylocmnflightdata") == 0) return DPCHAPPBRLYLOCMNFLIGHTDATA;
	else if (s.compare("dpchappbrlylocmnflightdo") == 0) return DPCHAPPBRLYLOCMNFLIGHTDO;
	else if (s.compare("dpchappbrlylocmnlegdata") == 0) return DPCHAPPBRLYLOCMNLEGDATA;
	else if (s.compare("dpchappbrlylocmnlegdo") == 0) return DPCHAPPBRLYLOCMNLEGDO;
	else if (s.compare("dpchappbrlylocmnsegmentdata") == 0) return DPCHAPPBRLYLOCMNSEGMENTDATA;
	else if (s.compare("dpchappbrlylocmnsegmentdo") == 0) return DPCHAPPBRLYLOCMNSEGMENTDO;
	else if (s.compare("dpchappbrlylocproxorgmnlocationdata") == 0) return DPCHAPPBRLYLOCPROXORGMNLOCATIONDATA;
	else if (s.compare("dpchappbrlylocproxorgmnlocationdo") == 0) return DPCHAPPBRLYLOCPROXORGMNLOCATIONDO;
	else if (s.compare("dpchappbrlylocrecdo") == 0) return DPCHAPPBRLYLOCRECDO;
	else if (s.compare("dpchappbrlylocvisorgmnlocationdata") == 0) return DPCHAPPBRLYLOCVISORGMNLOCATIONDATA;
	else if (s.compare("dpchappbrlylocvisorgmnlocationdo") == 0) return DPCHAPPBRLYLOCVISORGMNLOCATIONDO;
	else if (s.compare("dpchappbrlynavadmindata") == 0) return DPCHAPPBRLYNAVADMINDATA;
	else if (s.compare("dpchappbrlynavadmindo") == 0) return DPCHAPPBRLYNAVADMINDO;
	else if (s.compare("dpchappbrlynavbasedata") == 0) return DPCHAPPBRLYNAVBASEDATA;
	else if (s.compare("dpchappbrlynavbasedo") == 0) return DPCHAPPBRLYNAVBASEDO;
	else if (s.compare("dpchappbrlynavconnectdata") == 0) return DPCHAPPBRLYNAVCONNECTDATA;
	else if (s.compare("dpchappbrlynavconnectdo") == 0) return DPCHAPPBRLYNAVCONNECTDO;
	else if (s.compare("dpchappbrlynavdo") == 0) return DPCHAPPBRLYNAVDO;
	else if (s.compare("dpchappbrlyopr1nequipmentdata") == 0) return DPCHAPPBRLYOPR1NEQUIPMENTDATA;
	else if (s.compare("dpchappbrlyopr1nequipmentdo") == 0) return DPCHAPPBRLYOPR1NEQUIPMENTDO;
	else if (s.compare("dpchappbrlyoprdetaildata") == 0) return DPCHAPPBRLYOPRDETAILDATA;
	else if (s.compare("dpchappbrlyoprdetaildo") == 0) return DPCHAPPBRLYOPRDETAILDO;
	else if (s.compare("dpchappbrlyoprdo") == 0) return DPCHAPPBRLYOPRDO;
	else if (s.compare("dpchappbrlyoprlistdata") == 0) return DPCHAPPBRLYOPRLISTDATA;
	else if (s.compare("dpchappbrlyoprlistdo") == 0) return DPCHAPPBRLYOPRLISTDO;
	else if (s.compare("dpchappbrlyoprrecdo") == 0) return DPCHAPPBRLYOPRRECDO;
	else if (s.compare("dpchappbrlyprsadetaildata") == 0) return DPCHAPPBRLYPRSADETAILDATA;
	else if (s.compare("dpchappbrlyprsadetaildo") == 0) return DPCHAPPBRLYPRSADETAILDO;
	else if (s.compare("dpchappbrlyprsdetaildata") == 0) return DPCHAPPBRLYPRSDETAILDATA;
	else if (s.compare("dpchappbrlyprsdetaildo") == 0) return DPCHAPPBRLYPRSDETAILDO;
	else if (s.compare("dpchappbrlyprsdo") == 0) return DPCHAPPBRLYPRSDO;
	else if (s.compare("dpchappbrlyprslistdata") == 0) return DPCHAPPBRLYPRSLISTDATA;
	else if (s.compare("dpchappbrlyprslistdo") == 0) return DPCHAPPBRLYPRSLISTDO;
	else if (s.compare("dpchappbrlyprsrecdo") == 0) return DPCHAPPBRLYPRSRECDO;
	else if (s.compare("dpchappbrlypty1nequipmentdata") == 0) return DPCHAPPBRLYPTY1NEQUIPMENTDATA;
	else if (s.compare("dpchappbrlypty1nequipmentdo") == 0) return DPCHAPPBRLYPTY1NEQUIPMENTDO;
	else if (s.compare("dpchappbrlyptydetaildata") == 0) return DPCHAPPBRLYPTYDETAILDATA;
	else if (s.compare("dpchappbrlyptydetaildo") == 0) return DPCHAPPBRLYPTYDETAILDO;
	else if (s.compare("dpchappbrlyptydo") == 0) return DPCHAPPBRLYPTYDO;
	else if (s.compare("dpchappbrlyptylistdata") == 0) return DPCHAPPBRLYPTYLISTDATA;
	else if (s.compare("dpchappbrlyptylistdo") == 0) return DPCHAPPBRLYPTYLISTDO;
	else if (s.compare("dpchappbrlyptyrecdo") == 0) return DPCHAPPBRLYPTYRECDO;
	else if (s.compare("dpchappbrlyreg1nlocationdata") == 0) return DPCHAPPBRLYREG1NLOCATIONDATA;
	else if (s.compare("dpchappbrlyreg1nlocationdo") == 0) return DPCHAPPBRLYREG1NLOCATIONDO;
	else if (s.compare("dpchappbrlyregadstswitchdata") == 0) return DPCHAPPBRLYREGADSTSWITCHDATA;
	else if (s.compare("dpchappbrlyregadstswitchdo") == 0) return DPCHAPPBRLYREGADSTSWITCHDO;
	else if (s.compare("dpchappbrlyregdetaildata") == 0) return DPCHAPPBRLYREGDETAILDATA;
	else if (s.compare("dpchappbrlyregdetaildo") == 0) return DPCHAPPBRLYREGDETAILDO;
	else if (s.compare("dpchappbrlyregdo") == 0) return DPCHAPPBRLYREGDO;
	else if (s.compare("dpchappbrlyreglistdata") == 0) return DPCHAPPBRLYREGLISTDATA;
	else if (s.compare("dpchappbrlyreglistdo") == 0) return DPCHAPPBRLYREGLISTDO;
	else if (s.compare("dpchappbrlyregrecdo") == 0) return DPCHAPPBRLYREGRECDO;
	else if (s.compare("dpchappbrlyregsup1nregiondata") == 0) return DPCHAPPBRLYREGSUP1NREGIONDATA;
	else if (s.compare("dpchappbrlyregsup1nregiondo") == 0) return DPCHAPPBRLYREGSUP1NREGIONDO;
	else if (s.compare("dpchappbrlyresume") == 0) return DPCHAPPBRLYRESUME;
	else if (s.compare("dpchappbrlyrly1nnodedata") == 0) return DPCHAPPBRLYRLY1NNODEDATA;
	else if (s.compare("dpchappbrlyrly1nnodedo") == 0) return DPCHAPPBRLYRLY1NNODEDO;
	else if (s.compare("dpchappbrlyrlydetaildata") == 0) return DPCHAPPBRLYRLYDETAILDATA;
	else if (s.compare("dpchappbrlyrlydetaildo") == 0) return DPCHAPPBRLYRLYDETAILDO;
	else if (s.compare("dpchappbrlyrlydo") == 0) return DPCHAPPBRLYRLYDO;
	else if (s.compare("dpchappbrlyrlylistdata") == 0) return DPCHAPPBRLYRLYLISTDATA;
	else if (s.compare("dpchappbrlyrlylistdo") == 0) return DPCHAPPBRLYRLYLISTDO;
	else if (s.compare("dpchappbrlyrlyrecdo") == 0) return DPCHAPPBRLYRLYRECDO;
	else if (s.compare("dpchappbrlysegdetaildata") == 0) return DPCHAPPBRLYSEGDETAILDATA;
	else if (s.compare("dpchappbrlysegdetaildo") == 0) return DPCHAPPBRLYSEGDETAILDO;
	else if (s.compare("dpchappbrlysegdo") == 0) return DPCHAPPBRLYSEGDO;
	else if (s.compare("dpchappbrlyseglistdata") == 0) return DPCHAPPBRLYSEGLISTDATA;
	else if (s.compare("dpchappbrlyseglistdo") == 0) return DPCHAPPBRLYSEGLISTDO;
	else if (s.compare("dpchappbrlysegmnconnectiondata") == 0) return DPCHAPPBRLYSEGMNCONNECTIONDATA;
	else if (s.compare("dpchappbrlysegmnconnectiondo") == 0) return DPCHAPPBRLYSEGMNCONNECTIONDO;
	else if (s.compare("dpchappbrlysegmnlocationdata") == 0) return DPCHAPPBRLYSEGMNLOCATIONDATA;
	else if (s.compare("dpchappbrlysegmnlocationdo") == 0) return DPCHAPPBRLYSEGMNLOCATIONDO;
	else if (s.compare("dpchappbrlysegorgmnsegmentdata") == 0) return DPCHAPPBRLYSEGORGMNSEGMENTDATA;
	else if (s.compare("dpchappbrlysegorgmnsegmentdo") == 0) return DPCHAPPBRLYSEGORGMNSEGMENTDO;
	else if (s.compare("dpchappbrlysegpredata") == 0) return DPCHAPPBRLYSEGPREDATA;
	else if (s.compare("dpchappbrlysegrecdo") == 0) return DPCHAPPBRLYSEGRECDO;
	else if (s.compare("dpchappbrlyttb1nflightdata") == 0) return DPCHAPPBRLYTTB1NFLIGHTDATA;
	else if (s.compare("dpchappbrlyttb1nflightdo") == 0) return DPCHAPPBRLYTTB1NFLIGHTDO;
	else if (s.compare("dpchappbrlyttbdetaildata") == 0) return DPCHAPPBRLYTTBDETAILDATA;
	else if (s.compare("dpchappbrlyttbdetaildo") == 0) return DPCHAPPBRLYTTBDETAILDO;
	else if (s.compare("dpchappbrlyttbdo") == 0) return DPCHAPPBRLYTTBDO;
	else if (s.compare("dpchappbrlyttblistdata") == 0) return DPCHAPPBRLYTTBLISTDATA;
	else if (s.compare("dpchappbrlyttblistdo") == 0) return DPCHAPPBRLYTTBLISTDO;
	else if (s.compare("dpchappbrlyttbrecdo") == 0) return DPCHAPPBRLYTTBRECDO;
	else if (s.compare("dpchappbrlyttbref1nfiledata") == 0) return DPCHAPPBRLYTTBREF1NFILEDATA;
	else if (s.compare("dpchappbrlyttbref1nfiledo") == 0) return DPCHAPPBRLYTTBREF1NFILEDO;
	else if (s.compare("dpchappbrlyusgaaccessdata") == 0) return DPCHAPPBRLYUSGAACCESSDATA;
	else if (s.compare("dpchappbrlyusgaaccessdo") == 0) return DPCHAPPBRLYUSGAACCESSDO;
	else if (s.compare("dpchappbrlyusgdetaildata") == 0) return DPCHAPPBRLYUSGDETAILDATA;
	else if (s.compare("dpchappbrlyusgdetaildo") == 0) return DPCHAPPBRLYUSGDETAILDO;
	else if (s.compare("dpchappbrlyusgdo") == 0) return DPCHAPPBRLYUSGDO;
	else if (s.compare("dpchappbrlyusglistdata") == 0) return DPCHAPPBRLYUSGLISTDATA;
	else if (s.compare("dpchappbrlyusglistdo") == 0) return DPCHAPPBRLYUSGLISTDO;
	else if (s.compare("dpchappbrlyusgmnuserdata") == 0) return DPCHAPPBRLYUSGMNUSERDATA;
	else if (s.compare("dpchappbrlyusgmnuserdo") == 0) return DPCHAPPBRLYUSGMNUSERDO;
	else if (s.compare("dpchappbrlyusgrecdo") == 0) return DPCHAPPBRLYUSGRECDO;
	else if (s.compare("dpchappbrlyusr1nsessiondata") == 0) return DPCHAPPBRLYUSR1NSESSIONDATA;
	else if (s.compare("dpchappbrlyusr1nsessiondo") == 0) return DPCHAPPBRLYUSR1NSESSIONDO;
	else if (s.compare("dpchappbrlyusraaccessdata") == 0) return DPCHAPPBRLYUSRAACCESSDATA;
	else if (s.compare("dpchappbrlyusraaccessdo") == 0) return DPCHAPPBRLYUSRAACCESSDO;
	else if (s.compare("dpchappbrlyusrdetaildata") == 0) return DPCHAPPBRLYUSRDETAILDATA;
	else if (s.compare("dpchappbrlyusrdetaildo") == 0) return DPCHAPPBRLYUSRDETAILDO;
	else if (s.compare("dpchappbrlyusrdo") == 0) return DPCHAPPBRLYUSRDO;
	else if (s.compare("dpchappbrlyusrlistdata") == 0) return DPCHAPPBRLYUSRLISTDATA;
	else if (s.compare("dpchappbrlyusrlistdo") == 0) return DPCHAPPBRLYUSRLISTDO;
	else if (s.compare("dpchappbrlyusrmnusergroupdata") == 0) return DPCHAPPBRLYUSRMNUSERGROUPDATA;
	else if (s.compare("dpchappbrlyusrmnusergroupdo") == 0) return DPCHAPPBRLYUSRMNUSERGROUPDO;
	else if (s.compare("dpchappbrlyusrrecdo") == 0) return DPCHAPPBRLYUSRRECDO;
	else if (s.compare("dpchappdlgbrlyconnewdata") == 0) return DPCHAPPDLGBRLYCONNEWDATA;
	else if (s.compare("dpchappdlgbrlyconnewdo") == 0) return DPCHAPPDLGBRLYCONNEWDO;
	else if (s.compare("dpchappdlgbrlylegnewdata") == 0) return DPCHAPPDLGBRLYLEGNEWDATA;
	else if (s.compare("dpchappdlgbrlylegnewdo") == 0) return DPCHAPPDLGBRLYLEGNEWDO;
	else if (s.compare("dpchappdlgbrlynavloainidata") == 0) return DPCHAPPDLGBRLYNAVLOAINIDATA;
	else if (s.compare("dpchappdlgbrlynavloainido") == 0) return DPCHAPPDLGBRLYNAVLOAINIDO;
	else if (s.compare("dpchappdlgbrlyttbimpfltdata") == 0) return DPCHAPPDLGBRLYTTBIMPFLTDATA;
	else if (s.compare("dpchappdlgbrlyttbimpfltdo") == 0) return DPCHAPPDLGBRLYTTBIMPFLTDO;
	else if (s.compare("dpchappdlgbrlyttbnewdata") == 0) return DPCHAPPDLGBRLYTTBNEWDATA;
	else if (s.compare("dpchappdlgbrlyttbnewdo") == 0) return DPCHAPPDLGBRLYTTBNEWDO;
	else if (s.compare("dpchappdlgbrlyttbtrlorigdata") == 0) return DPCHAPPDLGBRLYTTBTRLORIGDATA;
	else if (s.compare("dpchappdlgbrlyttbtrlorigdo") == 0) return DPCHAPPDLGBRLYTTBTRLORIGDO;
	else if (s.compare("dpchapprootbrlylogin") == 0) return DPCHAPPROOTBRLYLOGIN;

	return(0);
};

string VecBrlyVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHENGBRLYACK) return("DpchEngBrlyAck");
	else if (ix == DPCHENGBRLYALERT) return("DpchEngBrlyAlert");
	else if (ix == DPCHENGBRLYCON1NRELAYDATA) return("DpchEngBrlyCon1NRelayData");
	else if (ix == DPCHENGBRLYCONCONMNEQUIPMENTDATA) return("DpchEngBrlyConConMNEquipmentData");
	else if (ix == DPCHENGBRLYCONDATA) return("DpchEngBrlyConData");
	else if (ix == DPCHENGBRLYCONDETAILDATA) return("DpchEngBrlyConDetailData");
	else if (ix == DPCHENGBRLYCONFIRM) return("DpchEngBrlyConfirm");
	else if (ix == DPCHENGBRLYCONHEADBARDATA) return("DpchEngBrlyConHeadbarData");
	else if (ix == DPCHENGBRLYCONLISTDATA) return("DpchEngBrlyConListData");
	else if (ix == DPCHENGBRLYCONMAPDATA) return("DpchEngBrlyConMapData");
	else if (ix == DPCHENGBRLYCONMAPIMAGE) return("DpchEngBrlyConMapImage");
	else if (ix == DPCHENGBRLYCONMNFLIGHTDATA) return("DpchEngBrlyConMNFlightData");
	else if (ix == DPCHENGBRLYCONMNSEGMENTDATA) return("DpchEngBrlyConMNSegmentData");
	else if (ix == DPCHENGBRLYCONPREDATA) return("DpchEngBrlyConPreData");
	else if (ix == DPCHENGBRLYCONRECDATA) return("DpchEngBrlyConRecData");
	else if (ix == DPCHENGBRLYCONREF1NSEGMENTDATA) return("DpchEngBrlyConRef1NSegmentData");
	else if (ix == DPCHENGBRLYFILDATA) return("DpchEngBrlyFilData");
	else if (ix == DPCHENGBRLYFILDETAILDATA) return("DpchEngBrlyFilDetailData");
	else if (ix == DPCHENGBRLYFILHEADBARDATA) return("DpchEngBrlyFilHeadbarData");
	else if (ix == DPCHENGBRLYFILLISTDATA) return("DpchEngBrlyFilListData");
	else if (ix == DPCHENGBRLYFILRECDATA) return("DpchEngBrlyFilRecData");
	else if (ix == DPCHENGBRLYFLT1NCONNECTIONDATA) return("DpchEngBrlyFlt1NConnectionData");
	else if (ix == DPCHENGBRLYFLTDATA) return("DpchEngBrlyFltData");
	else if (ix == DPCHENGBRLYFLTDETAILDATA) return("DpchEngBrlyFltDetailData");
	else if (ix == DPCHENGBRLYFLTEQP1NNODEDATA) return("DpchEngBrlyFltEqp1NNodeData");
	else if (ix == DPCHENGBRLYFLTEQPMNCONNECTIONDATA) return("DpchEngBrlyFltEqpMNConnectionData");
	else if (ix == DPCHENGBRLYFLTFAFAWAYPOINTDATA) return("DpchEngBrlyFltFafAWaypointData");
	else if (ix == DPCHENGBRLYFLTHEADBARDATA) return("DpchEngBrlyFltHeadbarData");
	else if (ix == DPCHENGBRLYFLTLISTDATA) return("DpchEngBrlyFltListData");
	else if (ix == DPCHENGBRLYFLTMNCONNECTIONDATA) return("DpchEngBrlyFltMNConnectionData");
	else if (ix == DPCHENGBRLYFLTMNLOCATIONDATA) return("DpchEngBrlyFltMNLocationData");
	else if (ix == DPCHENGBRLYFLTORGMNFLIGHTDATA) return("DpchEngBrlyFltOrgMNFlightData");
	else if (ix == DPCHENGBRLYFLTPREDATA) return("DpchEngBrlyFltPreData");
	else if (ix == DPCHENGBRLYFLTRECDATA) return("DpchEngBrlyFltRecData");
	else if (ix == DPCHENGBRLYFLTREF1NSEGMENTDATA) return("DpchEngBrlyFltRef1NSegmentData");
	else if (ix == DPCHENGBRLYLEG1NFLIGHTDATA) return("DpchEngBrlyLeg1NFlightData");
	else if (ix == DPCHENGBRLYLEGCOR1NCONNECTIONDATA) return("DpchEngBrlyLegCor1NConnectionData");
	else if (ix == DPCHENGBRLYLEGDATA) return("DpchEngBrlyLegData");
	else if (ix == DPCHENGBRLYLEGDETAILDATA) return("DpchEngBrlyLegDetailData");
	else if (ix == DPCHENGBRLYLEGHEADBARDATA) return("DpchEngBrlyLegHeadbarData");
	else if (ix == DPCHENGBRLYLEGLISTDATA) return("DpchEngBrlyLegListData");
	else if (ix == DPCHENGBRLYLEGMAPDATA) return("DpchEngBrlyLegMapData");
	else if (ix == DPCHENGBRLYLEGMAPIMAGE) return("DpchEngBrlyLegMapImage");
	else if (ix == DPCHENGBRLYLEGMNLOCATIONDATA) return("DpchEngBrlyLegMNLocationData");
	else if (ix == DPCHENGBRLYLEGORGMNLEGDATA) return("DpchEngBrlyLegOrgMNLegData");
	else if (ix == DPCHENGBRLYLEGPREDATA) return("DpchEngBrlyLegPreData");
	else if (ix == DPCHENGBRLYLEGRECDATA) return("DpchEngBrlyLegRecData");
	else if (ix == DPCHENGBRLYLOCBGN1NLEGDATA) return("DpchEngBrlyLocBgn1NLegData");
	else if (ix == DPCHENGBRLYLOCDATA) return("DpchEngBrlyLocData");
	else if (ix == DPCHENGBRLYLOCDETAILDATA) return("DpchEngBrlyLocDetailData");
	else if (ix == DPCHENGBRLYLOCEND1NLEGDATA) return("DpchEngBrlyLocEnd1NLegData");
	else if (ix == DPCHENGBRLYLOCEQP1NNODEDATA) return("DpchEngBrlyLocEqp1NNodeData");
	else if (ix == DPCHENGBRLYLOCEQPMNCONNECTIONDATA) return("DpchEngBrlyLocEqpMNConnectionData");
	else if (ix == DPCHENGBRLYLOCHEADBARDATA) return("DpchEngBrlyLocHeadbarData");
	else if (ix == DPCHENGBRLYLOCLISTDATA) return("DpchEngBrlyLocListData");
	else if (ix == DPCHENGBRLYLOCMAPDATA) return("DpchEngBrlyLocMapData");
	else if (ix == DPCHENGBRLYLOCMAPIMAGE) return("DpchEngBrlyLocMapImage");
	else if (ix == DPCHENGBRLYLOCMNFLIGHTDATA) return("DpchEngBrlyLocMNFlightData");
	else if (ix == DPCHENGBRLYLOCMNLEGDATA) return("DpchEngBrlyLocMNLegData");
	else if (ix == DPCHENGBRLYLOCMNSEGMENTDATA) return("DpchEngBrlyLocMNSegmentData");
	else if (ix == DPCHENGBRLYLOCPROXORGMNLOCATIONDATA) return("DpchEngBrlyLocProxOrgMNLocationData");
	else if (ix == DPCHENGBRLYLOCRECDATA) return("DpchEngBrlyLocRecData");
	else if (ix == DPCHENGBRLYLOCVISORGMNLOCATIONDATA) return("DpchEngBrlyLocVisOrgMNLocationData");
	else if (ix == DPCHENGBRLYNAVADMINDATA) return("DpchEngBrlyNavAdminData");
	else if (ix == DPCHENGBRLYNAVBASEDATA) return("DpchEngBrlyNavBaseData");
	else if (ix == DPCHENGBRLYNAVCONNECTDATA) return("DpchEngBrlyNavConnectData");
	else if (ix == DPCHENGBRLYNAVDATA) return("DpchEngBrlyNavData");
	else if (ix == DPCHENGBRLYNAVHEADBARDATA) return("DpchEngBrlyNavHeadbarData");
	else if (ix == DPCHENGBRLYOPR1NEQUIPMENTDATA) return("DpchEngBrlyOpr1NEquipmentData");
	else if (ix == DPCHENGBRLYOPRDATA) return("DpchEngBrlyOprData");
	else if (ix == DPCHENGBRLYOPRDETAILDATA) return("DpchEngBrlyOprDetailData");
	else if (ix == DPCHENGBRLYOPRHEADBARDATA) return("DpchEngBrlyOprHeadbarData");
	else if (ix == DPCHENGBRLYOPRLISTDATA) return("DpchEngBrlyOprListData");
	else if (ix == DPCHENGBRLYOPRRECDATA) return("DpchEngBrlyOprRecData");
	else if (ix == DPCHENGBRLYPRSADETAILDATA) return("DpchEngBrlyPrsADetailData");
	else if (ix == DPCHENGBRLYPRSDATA) return("DpchEngBrlyPrsData");
	else if (ix == DPCHENGBRLYPRSDETAILDATA) return("DpchEngBrlyPrsDetailData");
	else if (ix == DPCHENGBRLYPRSHEADBARDATA) return("DpchEngBrlyPrsHeadbarData");
	else if (ix == DPCHENGBRLYPRSLISTDATA) return("DpchEngBrlyPrsListData");
	else if (ix == DPCHENGBRLYPRSRECDATA) return("DpchEngBrlyPrsRecData");
	else if (ix == DPCHENGBRLYPTY1NEQUIPMENTDATA) return("DpchEngBrlyPty1NEquipmentData");
	else if (ix == DPCHENGBRLYPTYDATA) return("DpchEngBrlyPtyData");
	else if (ix == DPCHENGBRLYPTYDETAILDATA) return("DpchEngBrlyPtyDetailData");
	else if (ix == DPCHENGBRLYPTYHEADBARDATA) return("DpchEngBrlyPtyHeadbarData");
	else if (ix == DPCHENGBRLYPTYLISTDATA) return("DpchEngBrlyPtyListData");
	else if (ix == DPCHENGBRLYPTYRECDATA) return("DpchEngBrlyPtyRecData");
	else if (ix == DPCHENGBRLYREG1NLOCATIONDATA) return("DpchEngBrlyReg1NLocationData");
	else if (ix == DPCHENGBRLYREGADSTSWITCHDATA) return("DpchEngBrlyRegADstswitchData");
	else if (ix == DPCHENGBRLYREGDATA) return("DpchEngBrlyRegData");
	else if (ix == DPCHENGBRLYREGDETAILDATA) return("DpchEngBrlyRegDetailData");
	else if (ix == DPCHENGBRLYREGHEADBARDATA) return("DpchEngBrlyRegHeadbarData");
	else if (ix == DPCHENGBRLYREGLISTDATA) return("DpchEngBrlyRegListData");
	else if (ix == DPCHENGBRLYREGRECDATA) return("DpchEngBrlyRegRecData");
	else if (ix == DPCHENGBRLYREGSUP1NREGIONDATA) return("DpchEngBrlyRegSup1NRegionData");
	else if (ix == DPCHENGBRLYRLY1NNODEDATA) return("DpchEngBrlyRly1NNodeData");
	else if (ix == DPCHENGBRLYRLYDATA) return("DpchEngBrlyRlyData");
	else if (ix == DPCHENGBRLYRLYDETAILDATA) return("DpchEngBrlyRlyDetailData");
	else if (ix == DPCHENGBRLYRLYHEADBARDATA) return("DpchEngBrlyRlyHeadbarData");
	else if (ix == DPCHENGBRLYRLYLISTDATA) return("DpchEngBrlyRlyListData");
	else if (ix == DPCHENGBRLYRLYRECDATA) return("DpchEngBrlyRlyRecData");
	else if (ix == DPCHENGBRLYSEGDATA) return("DpchEngBrlySegData");
	else if (ix == DPCHENGBRLYSEGDETAILDATA) return("DpchEngBrlySegDetailData");
	else if (ix == DPCHENGBRLYSEGHEADBARDATA) return("DpchEngBrlySegHeadbarData");
	else if (ix == DPCHENGBRLYSEGLISTDATA) return("DpchEngBrlySegListData");
	else if (ix == DPCHENGBRLYSEGMNCONNECTIONDATA) return("DpchEngBrlySegMNConnectionData");
	else if (ix == DPCHENGBRLYSEGMNLOCATIONDATA) return("DpchEngBrlySegMNLocationData");
	else if (ix == DPCHENGBRLYSEGORGMNSEGMENTDATA) return("DpchEngBrlySegOrgMNSegmentData");
	else if (ix == DPCHENGBRLYSEGPREDATA) return("DpchEngBrlySegPreData");
	else if (ix == DPCHENGBRLYSEGRECDATA) return("DpchEngBrlySegRecData");
	else if (ix == DPCHENGBRLYSUSPEND) return("DpchEngBrlySuspend");
	else if (ix == DPCHENGBRLYTTB1NFLIGHTDATA) return("DpchEngBrlyTtb1NFlightData");
	else if (ix == DPCHENGBRLYTTBDATA) return("DpchEngBrlyTtbData");
	else if (ix == DPCHENGBRLYTTBDETAILDATA) return("DpchEngBrlyTtbDetailData");
	else if (ix == DPCHENGBRLYTTBHEADBARDATA) return("DpchEngBrlyTtbHeadbarData");
	else if (ix == DPCHENGBRLYTTBLISTDATA) return("DpchEngBrlyTtbListData");
	else if (ix == DPCHENGBRLYTTBRECDATA) return("DpchEngBrlyTtbRecData");
	else if (ix == DPCHENGBRLYTTBREF1NFILEDATA) return("DpchEngBrlyTtbRef1NFileData");
	else if (ix == DPCHENGBRLYUSGAACCESSDATA) return("DpchEngBrlyUsgAAccessData");
	else if (ix == DPCHENGBRLYUSGDATA) return("DpchEngBrlyUsgData");
	else if (ix == DPCHENGBRLYUSGDETAILDATA) return("DpchEngBrlyUsgDetailData");
	else if (ix == DPCHENGBRLYUSGHEADBARDATA) return("DpchEngBrlyUsgHeadbarData");
	else if (ix == DPCHENGBRLYUSGLISTDATA) return("DpchEngBrlyUsgListData");
	else if (ix == DPCHENGBRLYUSGMNUSERDATA) return("DpchEngBrlyUsgMNUserData");
	else if (ix == DPCHENGBRLYUSGRECDATA) return("DpchEngBrlyUsgRecData");
	else if (ix == DPCHENGBRLYUSR1NSESSIONDATA) return("DpchEngBrlyUsr1NSessionData");
	else if (ix == DPCHENGBRLYUSRAACCESSDATA) return("DpchEngBrlyUsrAAccessData");
	else if (ix == DPCHENGBRLYUSRDATA) return("DpchEngBrlyUsrData");
	else if (ix == DPCHENGBRLYUSRDETAILDATA) return("DpchEngBrlyUsrDetailData");
	else if (ix == DPCHENGBRLYUSRHEADBARDATA) return("DpchEngBrlyUsrHeadbarData");
	else if (ix == DPCHENGBRLYUSRLISTDATA) return("DpchEngBrlyUsrListData");
	else if (ix == DPCHENGBRLYUSRMNUSERGROUPDATA) return("DpchEngBrlyUsrMNUsergroupData");
	else if (ix == DPCHENGBRLYUSRRECDATA) return("DpchEngBrlyUsrRecData");
	else if (ix == DPCHENGDLGBRLYCONNEWDATA) return("DpchEngDlgBrlyConNewData");
	else if (ix == DPCHENGDLGBRLYLEGNEWDATA) return("DpchEngDlgBrlyLegNewData");
	else if (ix == DPCHENGDLGBRLYNAVLOAINIDATA) return("DpchEngDlgBrlyNavLoainiData");
	else if (ix == DPCHENGDLGBRLYTTBIMPFLTDATA) return("DpchEngDlgBrlyTtbImpfltData");
	else if (ix == DPCHENGDLGBRLYTTBNEWDATA) return("DpchEngDlgBrlyTtbNewData");
	else if (ix == DPCHENGDLGBRLYTTBTRLORIGDATA) return("DpchEngDlgBrlyTtbTrlorigData");
	else if (ix == DPCHENGSESSBRLYDATA) return("DpchEngSessBrlyData");
	else if (ix == DPCHAPPBRLYALERT) return("DpchAppBrlyAlert");
	else if (ix == DPCHAPPBRLYCON1NRELAYDATA) return("DpchAppBrlyCon1NRelayData");
	else if (ix == DPCHAPPBRLYCON1NRELAYDO) return("DpchAppBrlyCon1NRelayDo");
	else if (ix == DPCHAPPBRLYCONCONMNEQUIPMENTDATA) return("DpchAppBrlyConConMNEquipmentData");
	else if (ix == DPCHAPPBRLYCONCONMNEQUIPMENTDO) return("DpchAppBrlyConConMNEquipmentDo");
	else if (ix == DPCHAPPBRLYCONDETAILDATA) return("DpchAppBrlyConDetailData");
	else if (ix == DPCHAPPBRLYCONDETAILDO) return("DpchAppBrlyConDetailDo");
	else if (ix == DPCHAPPBRLYCONDO) return("DpchAppBrlyConDo");
	else if (ix == DPCHAPPBRLYCONLISTDATA) return("DpchAppBrlyConListData");
	else if (ix == DPCHAPPBRLYCONLISTDO) return("DpchAppBrlyConListDo");
	else if (ix == DPCHAPPBRLYCONMAPDATA) return("DpchAppBrlyConMapData");
	else if (ix == DPCHAPPBRLYCONMAPDO) return("DpchAppBrlyConMapDo");
	else if (ix == DPCHAPPBRLYCONMNFLIGHTDATA) return("DpchAppBrlyConMNFlightData");
	else if (ix == DPCHAPPBRLYCONMNFLIGHTDO) return("DpchAppBrlyConMNFlightDo");
	else if (ix == DPCHAPPBRLYCONMNSEGMENTDATA) return("DpchAppBrlyConMNSegmentData");
	else if (ix == DPCHAPPBRLYCONMNSEGMENTDO) return("DpchAppBrlyConMNSegmentDo");
	else if (ix == DPCHAPPBRLYCONPREDATA) return("DpchAppBrlyConPreData");
	else if (ix == DPCHAPPBRLYCONRECDO) return("DpchAppBrlyConRecDo");
	else if (ix == DPCHAPPBRLYCONREF1NSEGMENTDATA) return("DpchAppBrlyConRef1NSegmentData");
	else if (ix == DPCHAPPBRLYCONREF1NSEGMENTDO) return("DpchAppBrlyConRef1NSegmentDo");
	else if (ix == DPCHAPPBRLYFILDETAILDATA) return("DpchAppBrlyFilDetailData");
	else if (ix == DPCHAPPBRLYFILDETAILDO) return("DpchAppBrlyFilDetailDo");
	else if (ix == DPCHAPPBRLYFILDO) return("DpchAppBrlyFilDo");
	else if (ix == DPCHAPPBRLYFILLISTDATA) return("DpchAppBrlyFilListData");
	else if (ix == DPCHAPPBRLYFILLISTDO) return("DpchAppBrlyFilListDo");
	else if (ix == DPCHAPPBRLYFILRECDO) return("DpchAppBrlyFilRecDo");
	else if (ix == DPCHAPPBRLYFLT1NCONNECTIONDATA) return("DpchAppBrlyFlt1NConnectionData");
	else if (ix == DPCHAPPBRLYFLT1NCONNECTIONDO) return("DpchAppBrlyFlt1NConnectionDo");
	else if (ix == DPCHAPPBRLYFLTDETAILDATA) return("DpchAppBrlyFltDetailData");
	else if (ix == DPCHAPPBRLYFLTDETAILDO) return("DpchAppBrlyFltDetailDo");
	else if (ix == DPCHAPPBRLYFLTDO) return("DpchAppBrlyFltDo");
	else if (ix == DPCHAPPBRLYFLTEQP1NNODEDATA) return("DpchAppBrlyFltEqp1NNodeData");
	else if (ix == DPCHAPPBRLYFLTEQP1NNODEDO) return("DpchAppBrlyFltEqp1NNodeDo");
	else if (ix == DPCHAPPBRLYFLTEQPMNCONNECTIONDATA) return("DpchAppBrlyFltEqpMNConnectionData");
	else if (ix == DPCHAPPBRLYFLTEQPMNCONNECTIONDO) return("DpchAppBrlyFltEqpMNConnectionDo");
	else if (ix == DPCHAPPBRLYFLTFAFAWAYPOINTDATA) return("DpchAppBrlyFltFafAWaypointData");
	else if (ix == DPCHAPPBRLYFLTFAFAWAYPOINTDO) return("DpchAppBrlyFltFafAWaypointDo");
	else if (ix == DPCHAPPBRLYFLTLISTDATA) return("DpchAppBrlyFltListData");
	else if (ix == DPCHAPPBRLYFLTLISTDO) return("DpchAppBrlyFltListDo");
	else if (ix == DPCHAPPBRLYFLTMNCONNECTIONDATA) return("DpchAppBrlyFltMNConnectionData");
	else if (ix == DPCHAPPBRLYFLTMNCONNECTIONDO) return("DpchAppBrlyFltMNConnectionDo");
	else if (ix == DPCHAPPBRLYFLTMNLOCATIONDATA) return("DpchAppBrlyFltMNLocationData");
	else if (ix == DPCHAPPBRLYFLTMNLOCATIONDO) return("DpchAppBrlyFltMNLocationDo");
	else if (ix == DPCHAPPBRLYFLTORGMNFLIGHTDATA) return("DpchAppBrlyFltOrgMNFlightData");
	else if (ix == DPCHAPPBRLYFLTORGMNFLIGHTDO) return("DpchAppBrlyFltOrgMNFlightDo");
	else if (ix == DPCHAPPBRLYFLTPREDATA) return("DpchAppBrlyFltPreData");
	else if (ix == DPCHAPPBRLYFLTRECDO) return("DpchAppBrlyFltRecDo");
	else if (ix == DPCHAPPBRLYFLTREF1NSEGMENTDATA) return("DpchAppBrlyFltRef1NSegmentData");
	else if (ix == DPCHAPPBRLYFLTREF1NSEGMENTDO) return("DpchAppBrlyFltRef1NSegmentDo");
	else if (ix == DPCHAPPBRLYINIT) return("DpchAppBrlyInit");
	else if (ix == DPCHAPPBRLYLEG1NFLIGHTDATA) return("DpchAppBrlyLeg1NFlightData");
	else if (ix == DPCHAPPBRLYLEG1NFLIGHTDO) return("DpchAppBrlyLeg1NFlightDo");
	else if (ix == DPCHAPPBRLYLEGCOR1NCONNECTIONDATA) return("DpchAppBrlyLegCor1NConnectionData");
	else if (ix == DPCHAPPBRLYLEGCOR1NCONNECTIONDO) return("DpchAppBrlyLegCor1NConnectionDo");
	else if (ix == DPCHAPPBRLYLEGDETAILDATA) return("DpchAppBrlyLegDetailData");
	else if (ix == DPCHAPPBRLYLEGDETAILDO) return("DpchAppBrlyLegDetailDo");
	else if (ix == DPCHAPPBRLYLEGDO) return("DpchAppBrlyLegDo");
	else if (ix == DPCHAPPBRLYLEGLISTDATA) return("DpchAppBrlyLegListData");
	else if (ix == DPCHAPPBRLYLEGLISTDO) return("DpchAppBrlyLegListDo");
	else if (ix == DPCHAPPBRLYLEGMAPDATA) return("DpchAppBrlyLegMapData");
	else if (ix == DPCHAPPBRLYLEGMAPDO) return("DpchAppBrlyLegMapDo");
	else if (ix == DPCHAPPBRLYLEGMNLOCATIONDATA) return("DpchAppBrlyLegMNLocationData");
	else if (ix == DPCHAPPBRLYLEGMNLOCATIONDO) return("DpchAppBrlyLegMNLocationDo");
	else if (ix == DPCHAPPBRLYLEGORGMNLEGDATA) return("DpchAppBrlyLegOrgMNLegData");
	else if (ix == DPCHAPPBRLYLEGORGMNLEGDO) return("DpchAppBrlyLegOrgMNLegDo");
	else if (ix == DPCHAPPBRLYLEGPREDATA) return("DpchAppBrlyLegPreData");
	else if (ix == DPCHAPPBRLYLEGRECDO) return("DpchAppBrlyLegRecDo");
	else if (ix == DPCHAPPBRLYLOCBGN1NLEGDATA) return("DpchAppBrlyLocBgn1NLegData");
	else if (ix == DPCHAPPBRLYLOCBGN1NLEGDO) return("DpchAppBrlyLocBgn1NLegDo");
	else if (ix == DPCHAPPBRLYLOCDETAILDATA) return("DpchAppBrlyLocDetailData");
	else if (ix == DPCHAPPBRLYLOCDETAILDO) return("DpchAppBrlyLocDetailDo");
	else if (ix == DPCHAPPBRLYLOCDO) return("DpchAppBrlyLocDo");
	else if (ix == DPCHAPPBRLYLOCEND1NLEGDATA) return("DpchAppBrlyLocEnd1NLegData");
	else if (ix == DPCHAPPBRLYLOCEND1NLEGDO) return("DpchAppBrlyLocEnd1NLegDo");
	else if (ix == DPCHAPPBRLYLOCEQP1NNODEDATA) return("DpchAppBrlyLocEqp1NNodeData");
	else if (ix == DPCHAPPBRLYLOCEQP1NNODEDO) return("DpchAppBrlyLocEqp1NNodeDo");
	else if (ix == DPCHAPPBRLYLOCEQPMNCONNECTIONDATA) return("DpchAppBrlyLocEqpMNConnectionData");
	else if (ix == DPCHAPPBRLYLOCEQPMNCONNECTIONDO) return("DpchAppBrlyLocEqpMNConnectionDo");
	else if (ix == DPCHAPPBRLYLOCLISTDATA) return("DpchAppBrlyLocListData");
	else if (ix == DPCHAPPBRLYLOCLISTDO) return("DpchAppBrlyLocListDo");
	else if (ix == DPCHAPPBRLYLOCMAPDATA) return("DpchAppBrlyLocMapData");
	else if (ix == DPCHAPPBRLYLOCMAPDO) return("DpchAppBrlyLocMapDo");
	else if (ix == DPCHAPPBRLYLOCMNFLIGHTDATA) return("DpchAppBrlyLocMNFlightData");
	else if (ix == DPCHAPPBRLYLOCMNFLIGHTDO) return("DpchAppBrlyLocMNFlightDo");
	else if (ix == DPCHAPPBRLYLOCMNLEGDATA) return("DpchAppBrlyLocMNLegData");
	else if (ix == DPCHAPPBRLYLOCMNLEGDO) return("DpchAppBrlyLocMNLegDo");
	else if (ix == DPCHAPPBRLYLOCMNSEGMENTDATA) return("DpchAppBrlyLocMNSegmentData");
	else if (ix == DPCHAPPBRLYLOCMNSEGMENTDO) return("DpchAppBrlyLocMNSegmentDo");
	else if (ix == DPCHAPPBRLYLOCPROXORGMNLOCATIONDATA) return("DpchAppBrlyLocProxOrgMNLocationData");
	else if (ix == DPCHAPPBRLYLOCPROXORGMNLOCATIONDO) return("DpchAppBrlyLocProxOrgMNLocationDo");
	else if (ix == DPCHAPPBRLYLOCRECDO) return("DpchAppBrlyLocRecDo");
	else if (ix == DPCHAPPBRLYLOCVISORGMNLOCATIONDATA) return("DpchAppBrlyLocVisOrgMNLocationData");
	else if (ix == DPCHAPPBRLYLOCVISORGMNLOCATIONDO) return("DpchAppBrlyLocVisOrgMNLocationDo");
	else if (ix == DPCHAPPBRLYNAVADMINDATA) return("DpchAppBrlyNavAdminData");
	else if (ix == DPCHAPPBRLYNAVADMINDO) return("DpchAppBrlyNavAdminDo");
	else if (ix == DPCHAPPBRLYNAVBASEDATA) return("DpchAppBrlyNavBaseData");
	else if (ix == DPCHAPPBRLYNAVBASEDO) return("DpchAppBrlyNavBaseDo");
	else if (ix == DPCHAPPBRLYNAVCONNECTDATA) return("DpchAppBrlyNavConnectData");
	else if (ix == DPCHAPPBRLYNAVCONNECTDO) return("DpchAppBrlyNavConnectDo");
	else if (ix == DPCHAPPBRLYNAVDO) return("DpchAppBrlyNavDo");
	else if (ix == DPCHAPPBRLYOPR1NEQUIPMENTDATA) return("DpchAppBrlyOpr1NEquipmentData");
	else if (ix == DPCHAPPBRLYOPR1NEQUIPMENTDO) return("DpchAppBrlyOpr1NEquipmentDo");
	else if (ix == DPCHAPPBRLYOPRDETAILDATA) return("DpchAppBrlyOprDetailData");
	else if (ix == DPCHAPPBRLYOPRDETAILDO) return("DpchAppBrlyOprDetailDo");
	else if (ix == DPCHAPPBRLYOPRDO) return("DpchAppBrlyOprDo");
	else if (ix == DPCHAPPBRLYOPRLISTDATA) return("DpchAppBrlyOprListData");
	else if (ix == DPCHAPPBRLYOPRLISTDO) return("DpchAppBrlyOprListDo");
	else if (ix == DPCHAPPBRLYOPRRECDO) return("DpchAppBrlyOprRecDo");
	else if (ix == DPCHAPPBRLYPRSADETAILDATA) return("DpchAppBrlyPrsADetailData");
	else if (ix == DPCHAPPBRLYPRSADETAILDO) return("DpchAppBrlyPrsADetailDo");
	else if (ix == DPCHAPPBRLYPRSDETAILDATA) return("DpchAppBrlyPrsDetailData");
	else if (ix == DPCHAPPBRLYPRSDETAILDO) return("DpchAppBrlyPrsDetailDo");
	else if (ix == DPCHAPPBRLYPRSDO) return("DpchAppBrlyPrsDo");
	else if (ix == DPCHAPPBRLYPRSLISTDATA) return("DpchAppBrlyPrsListData");
	else if (ix == DPCHAPPBRLYPRSLISTDO) return("DpchAppBrlyPrsListDo");
	else if (ix == DPCHAPPBRLYPRSRECDO) return("DpchAppBrlyPrsRecDo");
	else if (ix == DPCHAPPBRLYPTY1NEQUIPMENTDATA) return("DpchAppBrlyPty1NEquipmentData");
	else if (ix == DPCHAPPBRLYPTY1NEQUIPMENTDO) return("DpchAppBrlyPty1NEquipmentDo");
	else if (ix == DPCHAPPBRLYPTYDETAILDATA) return("DpchAppBrlyPtyDetailData");
	else if (ix == DPCHAPPBRLYPTYDETAILDO) return("DpchAppBrlyPtyDetailDo");
	else if (ix == DPCHAPPBRLYPTYDO) return("DpchAppBrlyPtyDo");
	else if (ix == DPCHAPPBRLYPTYLISTDATA) return("DpchAppBrlyPtyListData");
	else if (ix == DPCHAPPBRLYPTYLISTDO) return("DpchAppBrlyPtyListDo");
	else if (ix == DPCHAPPBRLYPTYRECDO) return("DpchAppBrlyPtyRecDo");
	else if (ix == DPCHAPPBRLYREG1NLOCATIONDATA) return("DpchAppBrlyReg1NLocationData");
	else if (ix == DPCHAPPBRLYREG1NLOCATIONDO) return("DpchAppBrlyReg1NLocationDo");
	else if (ix == DPCHAPPBRLYREGADSTSWITCHDATA) return("DpchAppBrlyRegADstswitchData");
	else if (ix == DPCHAPPBRLYREGADSTSWITCHDO) return("DpchAppBrlyRegADstswitchDo");
	else if (ix == DPCHAPPBRLYREGDETAILDATA) return("DpchAppBrlyRegDetailData");
	else if (ix == DPCHAPPBRLYREGDETAILDO) return("DpchAppBrlyRegDetailDo");
	else if (ix == DPCHAPPBRLYREGDO) return("DpchAppBrlyRegDo");
	else if (ix == DPCHAPPBRLYREGLISTDATA) return("DpchAppBrlyRegListData");
	else if (ix == DPCHAPPBRLYREGLISTDO) return("DpchAppBrlyRegListDo");
	else if (ix == DPCHAPPBRLYREGRECDO) return("DpchAppBrlyRegRecDo");
	else if (ix == DPCHAPPBRLYREGSUP1NREGIONDATA) return("DpchAppBrlyRegSup1NRegionData");
	else if (ix == DPCHAPPBRLYREGSUP1NREGIONDO) return("DpchAppBrlyRegSup1NRegionDo");
	else if (ix == DPCHAPPBRLYRESUME) return("DpchAppBrlyResume");
	else if (ix == DPCHAPPBRLYRLY1NNODEDATA) return("DpchAppBrlyRly1NNodeData");
	else if (ix == DPCHAPPBRLYRLY1NNODEDO) return("DpchAppBrlyRly1NNodeDo");
	else if (ix == DPCHAPPBRLYRLYDETAILDATA) return("DpchAppBrlyRlyDetailData");
	else if (ix == DPCHAPPBRLYRLYDETAILDO) return("DpchAppBrlyRlyDetailDo");
	else if (ix == DPCHAPPBRLYRLYDO) return("DpchAppBrlyRlyDo");
	else if (ix == DPCHAPPBRLYRLYLISTDATA) return("DpchAppBrlyRlyListData");
	else if (ix == DPCHAPPBRLYRLYLISTDO) return("DpchAppBrlyRlyListDo");
	else if (ix == DPCHAPPBRLYRLYRECDO) return("DpchAppBrlyRlyRecDo");
	else if (ix == DPCHAPPBRLYSEGDETAILDATA) return("DpchAppBrlySegDetailData");
	else if (ix == DPCHAPPBRLYSEGDETAILDO) return("DpchAppBrlySegDetailDo");
	else if (ix == DPCHAPPBRLYSEGDO) return("DpchAppBrlySegDo");
	else if (ix == DPCHAPPBRLYSEGLISTDATA) return("DpchAppBrlySegListData");
	else if (ix == DPCHAPPBRLYSEGLISTDO) return("DpchAppBrlySegListDo");
	else if (ix == DPCHAPPBRLYSEGMNCONNECTIONDATA) return("DpchAppBrlySegMNConnectionData");
	else if (ix == DPCHAPPBRLYSEGMNCONNECTIONDO) return("DpchAppBrlySegMNConnectionDo");
	else if (ix == DPCHAPPBRLYSEGMNLOCATIONDATA) return("DpchAppBrlySegMNLocationData");
	else if (ix == DPCHAPPBRLYSEGMNLOCATIONDO) return("DpchAppBrlySegMNLocationDo");
	else if (ix == DPCHAPPBRLYSEGORGMNSEGMENTDATA) return("DpchAppBrlySegOrgMNSegmentData");
	else if (ix == DPCHAPPBRLYSEGORGMNSEGMENTDO) return("DpchAppBrlySegOrgMNSegmentDo");
	else if (ix == DPCHAPPBRLYSEGPREDATA) return("DpchAppBrlySegPreData");
	else if (ix == DPCHAPPBRLYSEGRECDO) return("DpchAppBrlySegRecDo");
	else if (ix == DPCHAPPBRLYTTB1NFLIGHTDATA) return("DpchAppBrlyTtb1NFlightData");
	else if (ix == DPCHAPPBRLYTTB1NFLIGHTDO) return("DpchAppBrlyTtb1NFlightDo");
	else if (ix == DPCHAPPBRLYTTBDETAILDATA) return("DpchAppBrlyTtbDetailData");
	else if (ix == DPCHAPPBRLYTTBDETAILDO) return("DpchAppBrlyTtbDetailDo");
	else if (ix == DPCHAPPBRLYTTBDO) return("DpchAppBrlyTtbDo");
	else if (ix == DPCHAPPBRLYTTBLISTDATA) return("DpchAppBrlyTtbListData");
	else if (ix == DPCHAPPBRLYTTBLISTDO) return("DpchAppBrlyTtbListDo");
	else if (ix == DPCHAPPBRLYTTBRECDO) return("DpchAppBrlyTtbRecDo");
	else if (ix == DPCHAPPBRLYTTBREF1NFILEDATA) return("DpchAppBrlyTtbRef1NFileData");
	else if (ix == DPCHAPPBRLYTTBREF1NFILEDO) return("DpchAppBrlyTtbRef1NFileDo");
	else if (ix == DPCHAPPBRLYUSGAACCESSDATA) return("DpchAppBrlyUsgAAccessData");
	else if (ix == DPCHAPPBRLYUSGAACCESSDO) return("DpchAppBrlyUsgAAccessDo");
	else if (ix == DPCHAPPBRLYUSGDETAILDATA) return("DpchAppBrlyUsgDetailData");
	else if (ix == DPCHAPPBRLYUSGDETAILDO) return("DpchAppBrlyUsgDetailDo");
	else if (ix == DPCHAPPBRLYUSGDO) return("DpchAppBrlyUsgDo");
	else if (ix == DPCHAPPBRLYUSGLISTDATA) return("DpchAppBrlyUsgListData");
	else if (ix == DPCHAPPBRLYUSGLISTDO) return("DpchAppBrlyUsgListDo");
	else if (ix == DPCHAPPBRLYUSGMNUSERDATA) return("DpchAppBrlyUsgMNUserData");
	else if (ix == DPCHAPPBRLYUSGMNUSERDO) return("DpchAppBrlyUsgMNUserDo");
	else if (ix == DPCHAPPBRLYUSGRECDO) return("DpchAppBrlyUsgRecDo");
	else if (ix == DPCHAPPBRLYUSR1NSESSIONDATA) return("DpchAppBrlyUsr1NSessionData");
	else if (ix == DPCHAPPBRLYUSR1NSESSIONDO) return("DpchAppBrlyUsr1NSessionDo");
	else if (ix == DPCHAPPBRLYUSRAACCESSDATA) return("DpchAppBrlyUsrAAccessData");
	else if (ix == DPCHAPPBRLYUSRAACCESSDO) return("DpchAppBrlyUsrAAccessDo");
	else if (ix == DPCHAPPBRLYUSRDETAILDATA) return("DpchAppBrlyUsrDetailData");
	else if (ix == DPCHAPPBRLYUSRDETAILDO) return("DpchAppBrlyUsrDetailDo");
	else if (ix == DPCHAPPBRLYUSRDO) return("DpchAppBrlyUsrDo");
	else if (ix == DPCHAPPBRLYUSRLISTDATA) return("DpchAppBrlyUsrListData");
	else if (ix == DPCHAPPBRLYUSRLISTDO) return("DpchAppBrlyUsrListDo");
	else if (ix == DPCHAPPBRLYUSRMNUSERGROUPDATA) return("DpchAppBrlyUsrMNUsergroupData");
	else if (ix == DPCHAPPBRLYUSRMNUSERGROUPDO) return("DpchAppBrlyUsrMNUsergroupDo");
	else if (ix == DPCHAPPBRLYUSRRECDO) return("DpchAppBrlyUsrRecDo");
	else if (ix == DPCHAPPDLGBRLYCONNEWDATA) return("DpchAppDlgBrlyConNewData");
	else if (ix == DPCHAPPDLGBRLYCONNEWDO) return("DpchAppDlgBrlyConNewDo");
	else if (ix == DPCHAPPDLGBRLYLEGNEWDATA) return("DpchAppDlgBrlyLegNewData");
	else if (ix == DPCHAPPDLGBRLYLEGNEWDO) return("DpchAppDlgBrlyLegNewDo");
	else if (ix == DPCHAPPDLGBRLYNAVLOAINIDATA) return("DpchAppDlgBrlyNavLoainiData");
	else if (ix == DPCHAPPDLGBRLYNAVLOAINIDO) return("DpchAppDlgBrlyNavLoainiDo");
	else if (ix == DPCHAPPDLGBRLYTTBIMPFLTDATA) return("DpchAppDlgBrlyTtbImpfltData");
	else if (ix == DPCHAPPDLGBRLYTTBIMPFLTDO) return("DpchAppDlgBrlyTtbImpfltDo");
	else if (ix == DPCHAPPDLGBRLYTTBNEWDATA) return("DpchAppDlgBrlyTtbNewData");
	else if (ix == DPCHAPPDLGBRLYTTBNEWDO) return("DpchAppDlgBrlyTtbNewDo");
	else if (ix == DPCHAPPDLGBRLYTTBTRLORIGDATA) return("DpchAppDlgBrlyTtbTrlorigData");
	else if (ix == DPCHAPPDLGBRLYTTBTRLORIGDO) return("DpchAppDlgBrlyTtbTrlorigDo");
	else if (ix == DPCHAPPROOTBRLYLOGIN) return("DpchAppRootBrlyLogin");

	return("");
};

