# file Makefile.inc
# make file paths for Brly combined daemon, release brlycmbd_ungenio
# author Alexander Wirthmueller
# date created: 8 Jan 2018
# modified: 8 Jan 2018

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin

